tunnel: be57f60b-ffaa-40af-b4d6-579f370a0d02

ingress:
  - hostname: tatooine.thewifijedi.com
    service: http://localhost:8080
    originRequest:
      connectTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveTimeout: 90s
  - hostname: workflows.thewifijedi.com
    service: http://localhost:5678
    originRequest:
      connectTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveTimeout: 90s
  - service: http_status:404
